### ISSUE TITLE
[st2express] st2api is binding 9101 before nginx can, causing nginx to not start

### ISSUE THREAD

**Issue by lattwood** [StackStorm/st2workroom#110]
Work aroundable by logging into the VM, and running `sudo service st2api stop && sudo service nginx start && sleep 5 && sudo service st2api start`

**Comment by jfryman** [comment]
Thanks for the workaround. We have a fix in https://github.com/StackStorm/st2workroom/pull/108 that will resolve this permanently when it lands.

**Comment by jfryman** [comment]
An updated vagrant image has been built that no longer has this issue. (v54). Please update with `vagrant box update` to get the latest bits and fix this issue.
