### ISSUE TITLE
"vagrant ssh st2express" fails

### ISSUE THREAD

**Issue by jonathanhle** [StackStorm/st2workroom#119]
==> st2express: Error: /Stage[main]/Profile::St2server/Python::Virtualenv[/etc/st2installer]/Exec[python_requirements_initial_install_/etc/st2installer/requirements.txt_/etc/st2installer/.venv]: Working directory '/opt/openstack/mistral' does not exist

Just an FYI - doesn't quite get there.

**Comment by jfryman** [comment]
Thanks for the report! Should be fixed up now.
