### ISSUE TITLE
st2express puppet-apply might give some races

### ISSUE THREAD

**Issue by dennybaa** [StackStorm/st2workroom#129]
During an install onto a clean ubuntu 14.04, we might see something like this:

https://gist.github.com/a58705245fabca6b02df

of course no other processes have been invoked to block apt.

**Comment by DoriftoShoes** [comment]
Are you running as root?

**Comment by arm4b** [comment]
I had the same thing 1 time for clean ubuntu14, running as root: 

``` sh
Error: Execution of '/usr/bin/apt-get -q -y -o DPkg::Options::=--force-confold install nodejs' returned 100: E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
```

But in my case I got another error before caused by internet disconnect: 

``` sh
Error: Could not start Service[docker-mongo]: Execution of '/etc/init.d/docker-mongo start' returned 1: Error: No such image or container: mongo
...
Get https://index.docker.io/v1/repositories/library/mongo/images: dial tcp: lookup index.docker.io on 10.0.2.3:53: read udp 10.0.2.3:53: i/o timeout
```

So my thinking was: they're related and just started again from clean ubuntu.
Leaving it here for more info.

**Comment by jfryman** [comment]
Resolved during our sprint
