### ISSUE TITLE
AIO installer: Hubot is installed by default

### ISSUE THREAD

**Issue by arm4b** [StackStorm/st2workroom#159]
Don't know bug or it's planned, but AIO installer `bootstrap-st2express | sh` installs Hubot by default.

I believe that expected behavior is to install Hubot only if (and after) `Enable ChatOps` checkbox is selected in UI here: 

![](http://docs.stackstorm.com/_images/st2installer_step_3.png)
At ^^ this point, it's already installed in system.

[AIO installer docs](http://docs.stackstorm.com/install/all_in_one.html#step-3-configure-chatops) says:

>  This step will setup Hubot and pre-configure it to connect to StackStorm as well as to your selected Chat service. While this is an optional feature and can be in the event that you have your own Hubot installation, or do not want to install this feature, we highly recommend experimenting with the feature in your daily operational workflows.

**Comment by jfryman** [comment]
This is the current behavior, and desired. Until we package it, we need to have it on the box otherwise NPM failures abound.
