### ISSUE TITLE
mDNS address st2express.local doesn't work on OSX out the box

### ISSUE THREAD

**Issue by enykeev** [StackStorm/st2workroom#16]
```
$ ping st2express.local
ping: cannot resolve st2express.local: Unknown host
```

although mDNS itself is working

```
$ ping mechanica-position.local
PING mechanica-position.local (127.0.0.1): 56 data bytes
64 bytes from 127.0.0.1: icmp_seq=0 ttl=64 time=0.041 ms
...
```

cc @warabe

**Comment by jfryman** [comment]
@enykeev are you using VirtualBox provider or VMWare Fusion provider for Vagrant?

**Comment by enykeev** [comment]
I can confirm this at least for VirtualBox.

**Comment by jfryman** [comment]
Ok. Try this....

Change `stacks/st2.yaml` and add the following config for `st2dev` or `st2express`, depending on how you're using it.

```
st2express:
  ...
  private_networks:
    - 172.168.200.10

```

I think this is a difference in providers, where VMWare just works and Virtualbox needs a bit of coercing.

**Comment by emedvedev** [comment]
@jfryman now it works, but the default domain in st2.yaml is "stackstorm.net" and not "local", so "st2express.local" (as mentioned in the README) wouldn't work out of the box anyway. I suppose, either the config or the readme should be changed to reflect this.

**Comment by jfryman** [comment]
@warabe it should still work, even with `stackstorm.net`. `avahi-daemon` is installed, supplying the `st2express.local` mDNS address over the private network.
