### ISSUE TITLE
actionrunner logs should be routed via rsyslog for st2express

### ISSUE THREAD

**Issue by manasdk** [StackStorm/st2workroom#33]
To make it easier to deal with logs :)

**Comment by jfryman** [comment]
:+1: Agreed.

**Comment by DoriftoShoes** [comment]
+:100:

**Comment by jfryman** [comment]
Are there working configs already for this?

**Comment by manasdk** [comment]
There is 

https://github.com/StackStorm/st2express/blob/master/vagrant/10-st2.syslog.conf
&
https://github.com/StackStorm/st2/blob/master/st2actions/conf/syslog.conf

**Comment by jfryman** [comment]
All set.

https://github.com/StackStorm/st2workroom/pull/71
