### ISSUE TITLE
CentOS: Installer complains "root is not in sudoers file" when installing packs. 

### ISSUE THREAD

**Issue by lakshmi-kannan** [StackStorm/st2workroom#341]
OS version: Cent OS 7. 
https://stackstorm-community.slack.com/archives/community/p1454376473002418

**Comment by lanthos** [comment]
Attached is the puppet.log file for when this occurred.

[puppet.log.zip](https://github.com/StackStorm/st2workroom/files/113273/puppet.log.zip)
