### ISSUE TITLE
Dependency error with Puppet installation of st2 on RHEL 6.5

### ISSUE THREAD

**Issue by elarrive** [StackStorm/st2workroom#346]
Notice: /Stage[main]/St2::Profile::Mistral/Vcsrepo[/opt/openstack/mistral]/revision: revision changed 'a24019f3485a9a0eacde12f0522b432fe0886477' to 'st2-1.2.0'
Error: Execution of '/bin/rpm -e python-devel-2.6.6-51.el6.x86_64' returned 1: error: Failed dependencies:
    python2-devel is needed by (installed) python-virtualenv-1.10.1-1.el6.noarch
    python-devel is needed by (installed) st2common-1.1.0-5.noarch
Error: /Stage[main]/Python::Install/Package[python-dev]/ensure: change from 2.6.6-51.el6 to absent failed: Execution of '/bin/rpm -e python-devel-2.6.6-51.el6.x86_64' returned 1: error: Failed dependencies:
    python2-devel is needed by (installed) python-virtualenv-1.10.1-1.el6.noarch
    python-devel is needed by (installed) st2common-1.1.0-5.noarch
Error: Execution of '/bin/rpm -e python-virtualenv-1.10.1-1.el6.noarch' returned 1: error: Failed dependencies:
    python-virtualenv is needed by (installed) python-virtualenv-clone-0.2.4-1.el6.noarch
    python-virtualenv is needed by (installed) python-virtualenvwrapper-3.5-2.el6.noarch
Error: /Stage[main]/Python::Install/Package[virtualenv]/ensure: change from 1.10.1-1.el6 to absent failed: Execution of '/bin/rpm -e python-virtualenv-1.10.1-1.el6.noarch' returned 1: error: Failed dependencies:
    python-virtualenv is needed by (installed) python-virtualenv-clone-0.2.4-1.el6.noarch
    python-virtualenv is needed by (installed) python-virtualenvwrapper-3.5-2.el6.noarch

**Comment by estee-tew** [comment]
https://stackstorm.slack.com/archives/stackstorm/p1455308886007427

**Comment by manasdk** [comment]
@elarrive Thanks for the report. Will take a look.

Does running `update-system` resolve the issue?

**Comment by elarrive** [comment]
@manasdk No problem  The installation was done using puppet apply on the fullinstall profile and so update-system was not installed.  I spoke with @DoriftoShoes about this also.  I don't know if this should be tracked in st2workroom or in puppet-st2.

**Comment by 7yl4r** [comment]
I stumbled here while debugging my puppet module and want to offer some help in case another stumbles in from google search:

" A is needed by (installed) B" is a dependency issue. You need to uninstall B before A using `requre`, `notify`, or similar. Else you can use "purged" instead of absent, but this will ignore *all* possible dependencies and might break something that depends on what you're uninstalling.
