### ISSUE TITLE
st2 package install fails

### ISSUE THREAD

**Issue by soumypau** [StackStorm/st2workroom#351]
Executing st2 run packs.install packs=st2  fails with exception 
Exception: Failed to install requirement "six>=1.9.0,<2.0": Collecting six<2.0,>=1.9.0
I get similar error while installing other packs as well. 

I verified six is already installed
###### 
##  /opt/stackstorm/st2/bin/pip show six

Metadata-Version: 2.0
Name: six
Version: 1.9.0
Summary: Python 2 and 3 compatibility utilities
Home-page: http://pypi.python.org/pypi/six/
Author: Benjamin Peterson
Author-email: benjamin@python.org
License: MIT
Location: /opt/stackstorm/st2/lib/python2.7/site-packages
Requires: 
###### 
###### 

 st2 run packs.install packs=st2
....................
id: 57493d188d1e0e188804b6e6
action.ref: packs.install
parameters: 
  packs:
- st2
  status: failed
  error: st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Setting up virtualenv for pack "st2"
  st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Removing virtualenv in "/opt/stackstorm/virtualenvs/st2"
  st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv for pack "st2" in "/opt/stackstorm/virtualenvs/st2"
  st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Creating virtualenv in "/opt/stackstorm/virtualenvs/st2" using Python binary "/opt/stackstorm/st2/bin/python"
  st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Running command "/opt/stackstorm/st2/bin/virtualenv -p /opt/stackstorm/st2/bin/python --always-copy /opt/stackstorm/virtualenvs/st2" to create virtualenv.
  st2.actions.python.SetupVirtualEnvironmentAction: DEBUG    Installing base requirements
  Traceback (most recent call last):
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 164, in <module>
    obj.run()
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2actions/runners/python_action_wrapper.py", line 103, in run
    output = action.run(**self._parameters)
  File "/opt/stackstorm/packs/packs/actions/pack_mgmt/setup_virtualenv.py", line 48, in run
    setup_pack_virtualenv(pack_name=pack_name, update=update, logger=self.logger)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/virtualenvs.py", line 86, in setup_pack_virtualenv
    install_requirement(virtualenv_path=virtualenv_path, requirement=requirement)
  File "/opt/stackstorm/st2/lib/python2.7/site-packages/st2common/util/virtualenvs.py", line 188, in install_requirement
    (requirement, stdout))
  Exception: Failed to install requirement "six>=1.9.0,<2.0": Collecting six<2.0,>=1.9.0

traceback: None
failed_on: setup_virtualenv
start_timestamp: 2016-05-28T06:39:20.933235Z
end_timestamp: 2016-05-28T06:39:59.867956Z
+--------------------------+-------------------------+-------------------+-------------------------+------------------------------+
| id                       | status                  | task              | action                  | start_timestamp              |
+--------------------------+-------------------------+-------------------+-------------------------+------------------------------+
| 57493d198d1e0e176a1f2a5f | succeeded (12s elapsed) | download          | packs.download          | Sat, 28 May 2016 06:39:21    |
|                          |                         |                   |                         | UTC                          |
| 57493d268d1e0e176a1f2a61 | succeeded (2s elapsed)  | virtualenv_prerun | packs.virtualenv_prerun | Sat, 28 May 2016 06:39:34    |
|                          |                         |                   |                         | UTC                          |
| 57493d288d1e0e176a1f2a63 | failed (22s elapsed)    | setup_virtualenv  | packs.setup_virtualenv  | Sat, 28 May 2016 06:39:36    |
|                          |                         |                   |                         | UTC                          |
+--------------------------+-------------------------+-------------------+-------------------------+------------------------------+
######

**Comment by sumeshkanayi** [comment]
Are you still facing this issue ?
I got it fixed with the help from some experts

https://github.com/StackStorm/st2/issues/2867#issuecomment-239594296

**Comment by arm4b** [comment]
@soumypau Are you installing StackStorm with `st2workroom`?
If yes, then it's totally deprecated method, see _Deprecation Warning_ in Readme.md.

Use https://docs.stackstorm.com/install/index.html instead.

**Comment by mayanksekhar** [comment]
Hi.. Thanks for your comments guys. 
We have got it working now .  We are facing an issue with packs though, will raise a new issue for that. 
Thanks again 
-Soumyadeep
