### ISSUE TITLE
Can't connect to st2express after running workroon

### ISSUE THREAD

**Issue by dzimine** [StackStorm/st2workroom#57]
Auth requests return 502, looks like nginx doesn't pass the request to `st2auth`. 
## Full notes

st2workroom, 02 Aug 2014
- change st2workroom/hieradata/workroom.yaml - st2::version: 0.13dev
- added mounts to stacks/st2.yaml
- `vagrant up st2express`
- takes forever (ok, long) to get st2express
- what SUCKS is it asks me for the mount password AFTER downloading the image == after ~30 min, can't tell exactly as I am sittign there waiting...
- Notice: Applied catalog in 218.43 seconds
- the only red portion is the following - but with big ST2 OK I don't worry about it: 

```
==> st2express: Notice: /Stage[main]/St2::Packs/St2::Pack[hubot]/Exec[install-st2-pack-hubot]/returns: executed successfully
==> st2express: Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/stackstorm/packs/hubot/config.yaml20150804-5724-x2dmkf.lock at 68:/opt/puppet/shared/st2/manifests/pack.pp
==> st2express: Error: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/stackstorm/packs/hubot/config.yaml20150804-5724-x2dmkf.lock at 68:/opt/puppet/shared/st2/manifests/pack.pp
==> st2express: Wrapped exception:
==> st2express: No such file or directory @ dir_s_rmdir - /opt/stackstorm/packs/hubot/config.yaml20150804-5724-x2dmkf.lock
==> st2express: Error: /Stage[main]/St2::Packs/St2::Pack[hubot]/File[/opt/stackstorm/packs/hubot/config.yaml]/ensure: change from absent to file failed: Could not set 'file' on ensure: No such file or directory @ dir_s_rmdir - /opt/stackstorm/packs/hubot/config.yaml20150804-5724-x2dmkf.lock at 68:/opt/puppet/shared/st2/manifests/pack.pp
```
- Running 1st time installer was intuitive (well, I first try to go to the WebUI directly and figured oh I don't have a user setup, ok, need the setup!)
- Config was good, excellent defaults, except I need to OPT-OUT from chatops
- But the installer begin to throw errors at me:

```
Host key verification failed.
[R10K::TaskRunner - ERROR] Task #<R10K::Task::Deployment::DeployEnvironments:0x00000000f3cff0> failed while running: Couldn't update git cache for .: "fatal: Not a git repository: '/root/.r10k/git/.'"
[R10K::TaskRunner - ERROR] Task #<R10K::Task::Deployment::PurgeEnvironments:0x00000000f3cf28> failed while running: Command git --git-dir /root/.r10k/git/. for-each-ref refs/heads --format %(refname) exited with 128: fatal: Not a git repository: '/root/.r10k/git/.'
Warning: You cannot collect exported resources without storeconfigs being set; the collection will be ignored at /opt/puppet/shared/nginx/manifests/resource/upstream.pp:89:5
Warning: /Apt_key[Add key: 056E8E56 from Apt::Source rabbitmq]: The id should be a full fingerprint (40 characters), see README.
Warning: /Apt_key[Add key: 68576280 from Apt::Source nodesource]: The id should be a full fingerprint (40 characters), see README.
Warning: /Apt_key[Add key: 6B8C7982 from Apt::Source stackstorm]: The id should be a full fingerprint (40 characters), see README.
Notice: /Stage[main]/Profile::Infrastructure/Exec[apply hostname]/returns: executed successfully
Notice: /Stage[main]/St2::Profile::Mistral/Python::Pip[python-mistralclient]/Exec[pip_install_python-mistralclient]/returns: executed successfully
Notice: /Stage[main]/St2::Profile::Client/Wget::Fetch[Download st2client requirements.txt]/Exec[wget-Download st2client requirements.txt]/returns: executed successfully
Notice: /Stage[main]/Profile::St2server/Python::Pip[uwsgi]/Exec[pip_install_uwsgi]/returns: executed successfully
Error: Could not start Service[rabbitmq-server]: Execution of '/etc/init.d/rabbitmq-server start' returned 1: * Starting message broker rabbitmq-server
* FAILED - check /var/log/rabbitmq/startup_\{log, _err\}
...fail!
Error: /Stage[main]/Rabbitmq::Service/Service[rabbitmq-server]/ensure: change from stopped to running failed: Could not start Service[rabbitmq-server]: Execution of '/etc/init.d/rabbitmq-server start' returned 1: * Starting message broker rabbitmq-server
* FAILED - check /var/log/rabbitmq/startup_\{log, _err\}
...fail!
Notice: /Stage[main]/Rabbitmq/Anchor[rabbitmq::end]: Dependency Service[rabbitmq-server] has failures: true
Warning: /Stage[main]/Rabbitmq/Anchor[rabbitmq::end]: Skipping because of failed dependencies
Notice: /Stage[main]/Rabbitmq::Install::Rabbitmqadmin/Staging::File[rabbitmqadmin]/Exec[/var/lib/rabbitmq/rabbitmqadmin]: Dependency Service[rabbitmq-server] has failures: true
Warning: /Stage[main]/Rabbitmq::Install::Rabbitmqadmin/Staging::File[rabbitmqadmin]/Exec[/var/lib/rabbitmq/rabbitmqadmin]: Skipping because of failed dependencies
Notice: /Stage[main]/Rabbitmq::Install::Rabbitmqadmin/File[/usr/local/bin/rabbitmqadmin]: Dependency Service[rabbitmq-server] has failures: true
Warning: /Stage[main]/Rabbitmq::Install::Rabbitmqadmin/File[/usr/local/bin/rabbitmqadmin]: Skipping because of failed dependencies
Notice: /Stage[main]/St2::Profile::Server/Wget::Fetch[Download st2server requirements.txt]/Exec[wget-Download st2server requirements.txt]/returns: executed successfully
Notice: /Stage[main]/St2::Profile::Web/Wget::Fetch[st2web]/Exec[wget-st2web]/returns: executed successfully
Notice: /Stage[main]/Nodejs/Exec[npm_proxy]/returns: executed successfully
Notice: /Stage[main]/Profile::St2server/Nginx::Resource::Vhost[st2api]/Concat[/etc/nginx/sites-available/st2api.conf]/Exec[concat_/etc/nginx/sites-available/st2api.conf]/returns: executed successfully

```
- Fine, it still sort of works, let's try to connect? Oops... can't authenticate. I can see that the user `admin` is created with the password i provided (ssh, su admin works fine). But I can't authenticate: st2auth service pukes: 

```
st2 auth admin
Password: 
ERROR: HTTPConnectionPool(host='localhost', port=9100): Max retries exceeded with url: /tokens (Caused by <class 'socket.error'>: [Errno 111] Connection refused)

vagrant@kickbox:/var/log/nginx$ tail -100 ssl-st2auth.access.log 
10.0.2.15 - root_cli [30/Jul/2015:18:26:59 +0000] "POST /tokens HTTP/1.1" 201 15
6 "-" "python-requests/2.2.1 CPython/2.7.6 Linux/3.16.0-30-generic"
172.168.50.11 - root_cli [04/Aug/2015:01:04:19 +0000] "POST /tokens HTTP/1.1" 20
1 156 "-" "python-requests/2.2.1 CPython/2.7.6 Linux/3.16.0-30-generic"
172.168.50.1 - - [04/Aug/2015:01:10:03 +0000] "OPTIONS /tokens HTTP/1.1" 204 0 "
https://172.168.50.11/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWeb
Kit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36"
172.168.50.1 - testu [04/Aug/2015:01:10:03 +0000] "POST /tokens HTTP/1.1" 401 60
5 "https://172.168.50.11/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) Apple
WebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36"
172.168.50.1 - - [04/Aug/2015:01:19:31 +0000] "OPTIONS /tokens HTTP/1.1" 502 583
 "https://172.168.50.11/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleW
ebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36"
172.168.50.1 - - [04/Aug/2015:01:19:47 +0000] "OPTIONS /tokens HTTP/1.1" 502 583
 "https://172.168.50.11/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleW
ebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36"
172.168.50.1 - - [04/Aug/2015:01:42:42 +0000] "GET / HTTP/1.1" 502 583 "-" "Mozi
lla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko
) Chrome/44.0.2403.125 Safari/537.36"
172.168.50.1 - - [04/Aug/2015:01:42:42 +0000] "GET /favicon.ico HTTP/1.1" 502 58
3 "https://172.168.50.11:9100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) 
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36"
172.168.50.1 - - [04/Aug/2015:01:43:06 +0000] "GET / HTTP/1.1" 502 583 "-" "Mozi
lla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko
) Chrome/44.0.2403.125 Safari/537.36"
172.168.50.1 - - [04/Aug/2015:01:43:06 +0000] "GET /favicon.ico HTTP/1.1" 502 58
3 "https://172.168.50.11:9100/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) 
AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36"
172.168.50.1 - - [04/Aug/2015:01:43:14 +0000] "GET /token HTTP/1.1" 502 583 "-" 
"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like 
Gecko) Chrome/44.0.2403.125 Safari/537.36"
172.168.50.1 - - [04/Aug/2015:01:43:14 +0000] "GET /favicon.ico HTTP/1.1" 502 58
3 "https://172.168.50.11:9100/token" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_
9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36"
172.168.50.1 - - [04/Aug/2015:01:43:32 +0000] "GET /tokens/ HTTP/1.1" 502 583 "-
" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, lik
e Gecko) Chrome/44.0.2403.125 Safari/537.36"
172.168.50.1 - - [04/Aug/2015:01:43:32 +0000] "GET /favicon.ico HTTP/1.1" 502 58
3 "https://172.168.50.11:9100/tokens/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 1
0_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36
"
172.168.50.1 - - [04/Aug/2015:01:45:08 +0000] "GET /tokens/ HTTP/1.1" 401 605 "-
" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, lik
e Gecko) Chrome/44.0.2403.125 Safari/537.36"
172.168.50.1 - admin [04/Aug/2015:01:45:31 +0000] "GET /tokens/ HTTP/1.1" 502 58
3 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML,
 like Gecko) Chrome/44.0.2403.125 Safari/537.36"
172.168.50.1 - - [04/Aug/2015:01:45:31 +0000] "GET /favicon.ico HTTP/1.1" 401 60
5 "https://172.168.50.11:9100/tokens/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 1
0_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/537.36
"
172.168.50.1 - admin [04/Aug/2015:01:45:31 +0000] "GET /favicon.ico HTTP/1.1" 50
2 583 "https://172.168.50.11:9100/tokens/" "Mozilla/5.0 (Macintosh; Intel Mac OS
 X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.125 Safari/53
7.36"
```
- Note that `/etc/st2/st2.conf` [st2auth] section is confusing, now that it's not used and the config is coming from `/etc/uwsgi.d/st2auth.ini`
- /var/log/st2auth.log is empty
- service st2auth status - stop/stopping???? It WAS running at the beginning.
- try to start it manually, took forever... but finally it's up
- Now it fails differently, but same 502, and doesn't look like we get to st2auth server anyways: 

```
vagrant@kickbox:/var/log/nginx$ st2 auth admin
Password: 
ERROR: HTTPConnectionPool(host='localhost', port=9100): Max retries exceeded with url: /tokens (Caused by <class 'httplib.BadStatusLine'>: '')
```
- Took a look at /etc/uwsgi.d/st2auth.ini to see may be something interesting there, but no luck, except it seems strange to me that we run both nginx and uwsgi on the same port 9100, how it works... 
- At this point it's 7:30 and I give up for a day.

**Comment by jfryman** [comment]
Ok, couple question. 
- What version of the Vagrant image did you use (`vagrant box list stackstorm/st2express`, most recent version)
- Can you post your `workroom.yaml`?

Let me discuss a few points.

> takes forever (ok, long) to get st2express
> what SUCKS is it asks me for the mount password AFTER downloading the image == after ~30 min, can't tell exactly as I am sittign there waiting...

Yes, this is how it's going to be for right now. Here's the thing. The download penalty is actually _less_ here, because all of the downloading that you would have had to do via the previous method. It just seems longer because there is less activity.

Where the time speed-up with this method _does_ come in are subsequent runs of `st2workroom`. After the initial tax, you can `destroy` / `recreate` with updated code within a minute, as you now get incremental updates from the time of the image being packaged.

This will continue to speed up when we move to Docker as core, as we'll be able to reduce the footprint even more, reducing the initial download time.

> Config was good, excellent defaults, except I need to OPT-OUT from chatops

Hopefully I'm not missing anything... but this is what I'm going for. I would think that we want to encourage ChatOps as a default option.

> Note that /etc/st2/st2.conf [st2auth] section is confusing, now that it's not used and the config is coming from /etc/uwsgi.d/st2auth.ini

I'm not sure what to do about this. Would you rather see it gone, or WSGI read those values?

**Comment by dzimine** [comment]
> What version of the Vagrant image did you use (vagrant box list stackstorm/st2express, most recent version)

```
 stackstorm/st2express                          (virtualbox, 0.13)     
```

> Can you post your workroom.yaml?
> 
> ```
> groups:
>   robots: {gid: '6000'}
> hubot::adapter: slack
> hubot::chat_alias: '!'
> hubot::dependencies: {hubot: '>= 2.6.0 < 3.0.0', hubot-scripts: '>= 2.5.0 < 3.0.0',
>   hubot-slack: '>=3.3.0 < 4.0.0', hubot-stackstorm: '>= 0.2.1 < 0.3.0'}
> hubot::env_export: {HUBOT_LOG_LEVEL: debug, HUBOT_SLACK_TOKEN: !!python/unicode 'xxx',
>   ST2_API: !!python/unicode 'https://kickbox:9101', ST2_AUTH_PASSWORD: .....,
>   ST2_AUTH_URL: !!python/unicode 'https://kickbox:9100', ST2_AUTH_USERNAME: chatops_bot,
>   ST2_WEBUI_URL: !!python/unicode 'https://kickbox'}
> hubot::external_scripts: [hubot-stackstorm]
> st2::api_url: !!python/unicode 'https://kickbox:9101'
> st2::auth_url: !!python/unicode 'https://kickbox:9100'
> st2::cli_api_url: !!python/unicode 'https://kickbox:9101'
> st2::cli_auth_url: !!python/unicode 'https://kickbox:9100'
> st2::installer_run: true
> st2::stanley::ssh_private_key: !!python/unicode "-----BEGIN RSA PRIVATE KEY-----\r\
>   <PRIVATE KEY WAS HERE> ==\r\n-----END RSA PRIVATE KEY-----"
> st2::stanley::ssh_public_key: !!python/unicode 'XXX...<PUBLIC KEY WAS HERE>=='
> st2::stanley::username: !!python/unicode 'stanley'
> system::hostname: !!python/unicode 'kickbox'
> users:
>   admin: {admin: true, password: !!python/unicode 'stackst0rm'}
>   chatops_bot: {password: ....., shell: /bin/false}
> ```

BTW this is another thing that bugs me: prior to provisioning, I manually edited the workroom.yaml to set up the version to 0.13dev, and now it's overwritten. 

I am at PEACE with asking the password in the middle, understand why and tradeoffs, just wanted to convey any hitch points. 

> > Note that /etc/st2/st2.conf [st2auth] section is confusing, now that it's not used and the config is coming from /etc/uwsgi.d/st2auth.ini
> 
> I'm not sure what to do about this. Would you rather see it gone, or WSGI read those values?

May be add the comments in st2.conf that "this section doesn't apply when st2auth is run via uwsgi, which is the case in most production environments, see uwsgi config at `/etc/uwsgi.d/st2auth.ini`.

**Comment by jfryman** [comment]
Got it.

`workroom.yaml` should now stay intact. Changed it so the installer reads/writes to a different file. (answers.yaml)

**Comment by jfryman** [comment]
All of these issues have been fixed. Closing. Please re-open or re-create new issue if problems appear.
